services:
  backend:
    build:
      context: ./back-end
    image: backend-image
    container_name: projecttwo-backend
    ports:
      - "9000:9000"

  frontend:
    #build:
      #context: ./front-end
    #image: frontend-image
    image: tgwrk/projecttwo-frontend:latest
    container_name: projecttwo-frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_API_HOST=http://backend:9000
    depends_on:
      - backend
